
[functions.gemini-generate]
enabled = true
verify_jwt = true
import_map = "./functions/gemini-generate/deno.json"

[functions.chat-with-rag]
enabled = true
verify_jwt = false
entrypoint = "./functions/chat-with-rag/index.ts"
